FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY etl/ ./etl/
COPY data/ ./data/
COPY logs/ ./logs/
COPY .env .
COPY scheduler.py .

CMD ["python", "scheduler.py"]